# SPDX-FileCopyrightText: 2026 4113Eng-wfs
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Third-party notice
# ------------------
# This module reads EXIF/XMP metadata generated by DJI drones and stored
# using DJI's proprietary XMP namespace (drone-dji:).
# DJI, the DJI logo and all DJI product names are trademarks or registered
# trademarks of SZ DJI Technology Co., Ltd.
# Sensor specifications and model identifiers are reproduced from publicly
# available DJI product documentation for interoperability purposes.
"""
drone_mf_attributes.py — OGC Moving Features drone attribute extraction
for the GIMI Imagery Workbench plugin.

Converts a ``DJIImageMetadata`` instance (from ``dji_adapter``) **or** any
raw EXIF/XMP dict scraped from a drone image into the ``DroneTrackPoint``
field set defined in the Cesium COP Dashboard moving-features domain.

The mapping follows:

    DJI XMP / EXIF field          →  DroneTrackPoint field
    ──────────────────────────────────────────────────────
    GPSLatitude / GPSLongitude    →  latitude / longitude
    GPSAltitude                   →  altitude_m  (ASL)
    RelativeAltitude              →  altitude_m  (AGL, preferred)
    FlightYawDegree               →  yaw_deg / heading_deg
    FlightPitchDegree             →  pitch_deg
    FlightRollDegree              →  roll_deg
    GimbalYawDegree               →  gimbal_yaw_deg
    GimbalPitchDegree             →  gimbal_pitch_deg
    GimbalRollDegree              →  gimbal_roll_deg
    drone serial / Make+Model     →  mqtt_client_id (fallback)
    FocalLength + sensor dims     →  camera_fov_h_deg / camera_fov_v_deg
    DroneType / Model keywords    →  drone_type_code (best-guess from DRONE_TYPES)

All fields that cannot be determined from the image metadata are set to
``None`` (numeric/bool) or ``""`` (string) so the downstream provenance
JSON / STAC item always has a consistent schema.

Usage::

    from .drone_mf_attributes import DroneMFAttributes

    # From a DJIImageMetadata object
    attrs = DroneMFAttributes.from_dji_meta(meta, track_id="IMG_0001")

    # From a raw dict (e.g. pillow-heif XMP dict or custom EXIF scraper)
    attrs = DroneMFAttributes.from_xmp_dict(xmp_dict, track_id="IMG_0001")

    # Embed into a provenance dict
    provenance["drone_moving_feature"] = attrs.to_dict()

    # Use as STAC extra_fields
    stac_props.update(attrs.to_stac_properties())
"""
from __future__ import annotations

import math
import os
import re
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, Optional

# ---------------------------------------------------------------------------
# Sensor defaults used when XMP focal-length / sensor dimensions are absent.
# Keyed by lowercase model-name fragment → (sensor_w_mm, sensor_h_mm).
# Source: DJI product pages + EXIF community data.
# ---------------------------------------------------------------------------
_SENSOR_DIMS: Dict[str, tuple] = {
    "mini 4 pro":        (9.6,   7.2),
    "mini 3 pro":        (9.6,   7.2),
    "mini 3":            (9.6,   7.2),
    "mini 2":            (6.17,  4.63),
    "mini se":           (6.17,  4.63),
    "mavic 3":           (17.3,  13.0),
    "mavic 3 pro":       (17.3,  13.0),
    "mavic 3 classic":   (17.3,  13.0),
    "mavic 3 enterprise":(17.3,  13.0),
    "mavic air 2s":      (13.2,   8.8),
    "mavic air 2":        (6.4,   4.8),
    "mavic air":          (6.17,  4.63),
    "mavic 2 pro":       (13.2,   8.8),
    "mavic 2 zoom":       (6.17,  4.63),
    "mavic pro":          (6.17,  4.63),
    "phantom 4 rtk":      (13.2,   8.8),
    "phantom 4 pro":      (13.2,   8.8),
    "phantom 4":          (6.17,  4.63),
    "phantom 3":          (6.17,  4.63),
    "inspire 2":         (17.3,  13.0),
    "matrice 300":        (13.2,   8.8),
    "matrice 350":        (13.2,   8.8),
    "matrice 30":         (9.6,   7.2),
    "m30":                (9.6,   7.2),
    "agras":              (6.17,  4.63),
    "neo":                (6.17,  4.63),
}

# ---------------------------------------------------------------------------
# Keyword → DRONE_TYPES code mapping (mirrors backend moving_feature_types.py)
# Only used for best-guess type resolution; defaults to 0 (Unknown).
# ---------------------------------------------------------------------------
_MODEL_TO_TYPE_CODE: Dict[str, int] = {
    "mini":             1,   # Consumer Quadrotor (DJI Mini series)
    "mavic air":        2,   # Consumer Hexarotor (closest match)
    "mavic":            1,   # Consumer Quadrotor
    "neo":              1,
    "agras":           14,   # Agricultural / Multirotor Professional
    "matrice":         10,   # Professional Survey/Mapping
    "phantom 4 rtk":   10,
    "phantom 4 pro":   10,
    "phantom":          1,
    "inspire":         11,   # Professional Inspection
    "fpv":             40,   # FPV Racing
    "avata":           40,
    "tello":            1,
}


def _fov_from_focal(focal_mm: Optional[float], sensor_dim_mm: float) -> Optional[float]:
    """Return field-of-view in degrees given focal length and sensor dimension."""
    if focal_mm and focal_mm > 0:
        return math.degrees(2.0 * math.atan(sensor_dim_mm / (2.0 * focal_mm)))
    return None


def _guess_type_code(model: str) -> int:
    """Best-effort mapping of drone model string → DRONE_TYPES integer code."""
    low = model.lower()
    for fragment, code in _MODEL_TO_TYPE_CODE.items():
        if fragment in low:
            return code
    return 0


def _safe_float(v: Any) -> Optional[float]:
    """Return float or None; never raises."""
    try:
        return float(v) if v is not None else None
    except (TypeError, ValueError):
        return None


def _safe_int(v: Any) -> Optional[int]:
    try:
        return int(v) if v is not None else None
    except (TypeError, ValueError):
        return None


@dataclass
class DroneMFAttributes:
    """Flat dataclass matching the DroneTrackPoint schema from the COP backend.

    Fields that cannot be extracted from the image metadata are ``None`` /
    ``""`` so the record is always schema-complete.  Call ``to_dict()`` for
    JSON serialisation and ``to_stac_properties()`` for STAC Item embedding.
    """

    # ── Identity ──────────────────────────────────────────────────────────────
    track_id:           str   = ""
    name:               str   = ""
    drone_type_code:    int   = 0
    source:             str   = "gimi_exif"

    # ── Position ──────────────────────────────────────────────────────────────
    latitude:           Optional[float] = None
    longitude:          Optional[float] = None
    altitude_m:         Optional[float] = None
    altitude_agl:       Optional[bool]  = None

    # ── Flight attitude ───────────────────────────────────────────────────────
    roll_deg:           Optional[float] = None
    pitch_deg:          Optional[float] = None
    yaw_deg:            Optional[float] = None

    # ── Navigation ────────────────────────────────────────────────────────────
    heading_deg:        Optional[float] = None
    speed_mps:          Optional[float] = None
    vertical_speed_mps: Optional[float] = None

    # ── Gimbal / camera ───────────────────────────────────────────────────────
    gimbal_roll_deg:    Optional[float] = None
    gimbal_pitch_deg:   Optional[float] = None
    gimbal_yaw_deg:     Optional[float] = None
    gimbal_world_frame: bool            = True
    camera_fov_h_deg:   Optional[float] = None
    camera_fov_v_deg:   Optional[float] = None
    zoom_factor:        Optional[float] = None
    recording:          Optional[bool]  = None
    photo_interval_s:   Optional[float] = None

    # ── Flight telemetry ──────────────────────────────────────────────────────
    battery_pct:        Optional[float] = None
    flight_time_s:      Optional[float] = None
    home_latitude:      Optional[float] = None
    home_longitude:     Optional[float] = None
    distance_to_home_m: Optional[float] = None
    gps_satellites:     Optional[int]   = None
    gps_signal_level:   Optional[int]   = None
    wind_speed_mps:     Optional[float] = None
    wind_dir_deg:       Optional[float] = None

    # ── MQTT ──────────────────────────────────────────────────────────────────
    mqtt_client_id:     str = ""
    mqtt_topic:         str = ""
    mqtt_broker:        str = ""

    # ── Swarm ─────────────────────────────────────────────────────────────────
    swarm_id:           str = ""
    node_id:            str = ""

    # ── Mission ───────────────────────────────────────────────────────────────
    mission_id:         str            = ""
    waypoint_index:     Optional[int]  = None
    return_to_home:     Optional[bool] = None

    # ── Datetime (ISO-8601 UTC string) ────────────────────────────────────────
    time_utc:           str = ""

    # ── Standard metadata derived from type code ──────────────────────────────
    mav_type:           Optional[int] = None
    stanag_4586_class:  str = ""
    faa_category:       str = ""
    mgcp_fcode:         str = "GB015"

    # ── Extra / passthrough ───────────────────────────────────────────────────
    extra:              Dict[str, Any] = field(default_factory=dict)

    # -------------------------------------------------------------------------
    # Factory — from DJIImageMetadata
    # -------------------------------------------------------------------------
    @classmethod
    def from_dji_meta(
        cls,
        meta,                          # DJIImageMetadata instance
        track_id: str = "",
        mqtt_client_id: str = "",
        mqtt_topic: str = "",
        mqtt_broker: str = "",
        mission_id: str = "",
    ) -> "DroneMFAttributes":
        """Build from a ``DJIImageMetadata`` dataclass instance.

        ``track_id`` defaults to the image filename stem if not provided.
        ``mqtt_*`` and ``mission_id`` come from the caller (not in EXIF).
        """
        tid = track_id or (os.path.splitext(os.path.basename(meta.path))[0] if meta.path else "")
        model = (getattr(meta, "model", "") or "").strip()
        serial = (getattr(meta, "serial_number", "") or "").strip()

        # Prefer relative altitude (AGL) from XMP; fall back to GPS ASL
        agl = getattr(meta, "relative_altitude", None)
        asl = getattr(meta, "gps_altitude", None)
        if agl is not None:
            alt   = _safe_float(agl)
            is_agl = True
        else:
            alt   = _safe_float(asl)
            is_agl = False

        # FoV from focal length + sensor dimensions
        fl = _safe_float(getattr(meta, "focal_length_mm", None))
        sw, sh = _sensor_dims_for_model(model)
        fov_h = _fov_from_focal(fl, sw)
        fov_v = _fov_from_focal(fl, sh)

        # MQTT client ID fallback: serial number or "DJI-<model>"
        if not mqtt_client_id:
            mqtt_client_id = serial or (f"DJI-{model}".rstrip("-") if model else "")

        # datetime → ISO-8601 UTC string
        dt = getattr(meta, "datetime_taken", None)
        time_utc = dt.isoformat() if dt else ""

        type_code = _guess_type_code(model)
        type_info = _resolve_type_info(type_code)

        return cls(
            track_id           = tid,
            name               = f"{model} {serial}".strip() or tid,
            drone_type_code    = type_code,
            source             = "gimi_exif",
            latitude           = _safe_float(getattr(meta, "latitude",  None)),
            longitude          = _safe_float(getattr(meta, "longitude", None)),
            altitude_m         = alt,
            altitude_agl       = is_agl,
            roll_deg           = _safe_float(getattr(meta, "flight_roll",  None)),
            pitch_deg          = _safe_float(getattr(meta, "flight_pitch", None)),
            yaw_deg            = _safe_float(getattr(meta, "flight_yaw",   None)),
            heading_deg        = _safe_float(getattr(meta, "flight_yaw",   None)),
            gimbal_roll_deg    = _safe_float(getattr(meta, "gimbal_roll",  None)),
            gimbal_pitch_deg   = _safe_float(getattr(meta, "gimbal_pitch", None)),
            gimbal_yaw_deg     = _safe_float(getattr(meta, "gimbal_yaw",   None)),
            gimbal_world_frame = True,   # DJI SDK reports stabilised world angles
            camera_fov_h_deg   = fov_h,
            camera_fov_v_deg   = fov_v,
            mqtt_client_id     = mqtt_client_id,
            mqtt_topic         = mqtt_topic,
            mqtt_broker        = mqtt_broker,
            mission_id         = mission_id,
            time_utc           = time_utc,
            mav_type           = type_info.get("mav_type"),
            stanag_4586_class  = type_info.get("stanag_4586_class", ""),
            faa_category       = type_info.get("faa_category", ""),
            mgcp_fcode         = type_info.get("mgcp_fcode", "GB015"),
        )

    # -------------------------------------------------------------------------
    # Factory — from raw XMP / EXIF dict
    # -------------------------------------------------------------------------
    @classmethod
    def from_xmp_dict(
        cls,
        xmp: Dict[str, Any],
        track_id: str = "",
        model: str = "",
        serial: str = "",
        mqtt_client_id: str = "",
        mqtt_topic: str = "",
        mqtt_broker: str = "",
        mission_id: str = "",
        image_path: str = "",
    ) -> "DroneMFAttributes":
        """Build from a flat XMP key→value dict (e.g. from pillow-heif or exiftool).

        Recognised XMP namespaces:
          ``drone-dji:``   DJI standard XMP (EXIF/XMP in JPEG/HEIF)
          ``Camera:``      non-DJI generic drone XMP
          ``exif:``        EXIF-mapped fields (GPS, FocalLength)

        All keys are stripped of their namespace prefix before matching so
        both ``drone-dji:FlightYawDegree`` and bare ``FlightYawDegree`` work.
        """
        def _get(*keys: str) -> Any:
            """Return first matching value from xmp, ignoring namespace prefix."""
            for k in keys:
                if k in xmp:
                    return xmp[k]
                # Try stripping namespace prefix
                bare = k.split(":")[-1]
                for xk, xv in xmp.items():
                    if xk.split(":")[-1] == bare:
                        return xv
            return None

        tid = track_id or os.path.splitext(os.path.basename(image_path))[0] if image_path else ""
        model = model or str(_get("Model", "drone-dji:DroneType", "Camera:DroneType") or "")
        serial = serial or str(_get("SerialNumber", "drone-dji:DroneSerialNumber") or "")

        # Altitude: prefer RelativeAltitude (AGL), fall back to GPSAltitude
        agl_raw = _get("RelativeAltitude", "drone-dji:RelativeAltitude")
        asl_raw = _get("GPSAltitude", "exif:GPSAltitude")
        if agl_raw is not None:
            alt   = _safe_float(agl_raw)
            is_agl = True
        else:
            alt   = _safe_float(asl_raw)
            is_agl = False

        # Focal length → FoV
        fl  = _safe_float(_get("FocalLength", "exif:FocalLength", "drone-dji:FocalLength"))
        sw, sh = _sensor_dims_for_model(model)
        fov_h = _fov_from_focal(fl, sw)
        fov_v = _fov_from_focal(fl, sh)

        if not mqtt_client_id:
            mqtt_client_id = serial or (f"DJI-{model}".rstrip("-") if model else "")

        type_code = _guess_type_code(model)
        type_info = _resolve_type_info(type_code)

        return cls(
            track_id           = tid,
            name               = f"{model} {serial}".strip() or tid,
            drone_type_code    = type_code,
            source             = "gimi_xmp",
            latitude           = _safe_float(_get("GPSLatitude",  "exif:GPSLatitude")),
            longitude          = _safe_float(_get("GPSLongitude", "exif:GPSLongitude")),
            altitude_m         = alt,
            altitude_agl       = is_agl,
            roll_deg           = _safe_float(_get("FlightRollDegree",  "drone-dji:FlightRollDegree")),
            pitch_deg          = _safe_float(_get("FlightPitchDegree", "drone-dji:FlightPitchDegree")),
            yaw_deg            = _safe_float(_get("FlightYawDegree",   "drone-dji:FlightYawDegree")),
            heading_deg        = _safe_float(_get("FlightYawDegree",   "drone-dji:FlightYawDegree",
                                                   "Heading", "CourseAngle")),
            gimbal_roll_deg    = _safe_float(_get("GimbalRollDegree",  "drone-dji:GimbalRollDegree")),
            gimbal_pitch_deg   = _safe_float(_get("GimbalPitchDegree", "drone-dji:GimbalPitchDegree")),
            gimbal_yaw_deg     = _safe_float(_get("GimbalYawDegree",   "drone-dji:GimbalYawDegree")),
            gimbal_world_frame = True,
            camera_fov_h_deg   = fov_h,
            camera_fov_v_deg   = fov_v,
            zoom_factor        = _safe_float(_get("ZoomRatio", "DigitalZoomRatio")),
            battery_pct        = _safe_float(_get("BatteryLevel", "drone-dji:BatteryLevel",
                                                   "Battery", "BatteryPercent")),
            flight_time_s      = _safe_float(_get("FlightTime", "drone-dji:FlightTime")),
            home_latitude      = _safe_float(_get("HomePointLatitude",  "drone-dji:HomePointLatitude")),
            home_longitude     = _safe_float(_get("HomePointLongitude", "drone-dji:HomePointLongitude")),
            gps_satellites     = _safe_int(_get("GPSSatellites", "SatellitesUsed")),
            wind_speed_mps     = _safe_float(_get("WindSpeed", "WindSpeedMPS")),
            wind_dir_deg       = _safe_float(_get("WindDirection")),
            mqtt_client_id     = mqtt_client_id,
            mqtt_topic         = mqtt_topic,
            mqtt_broker        = mqtt_broker,
            mission_id         = mission_id,
            time_utc           = str(_get("DateTimeOriginal", "DateTime", "exif:DateTimeOriginal") or ""),
            mav_type           = type_info.get("mav_type"),
            stanag_4586_class  = type_info.get("stanag_4586_class", ""),
            faa_category       = type_info.get("faa_category", ""),
            mgcp_fcode         = type_info.get("mgcp_fcode", "GB015"),
        )

    # -------------------------------------------------------------------------
    # Serialisation
    # -------------------------------------------------------------------------
    def to_dict(self) -> Dict[str, Any]:
        """Return the full attribute set as a JSON-serialisable dict.

        Suitable for embedding under ``provenance["drone_moving_feature"]``.
        """
        return asdict(self)

    def to_stac_properties(self) -> Dict[str, Any]:
        """Return a flat dict of ``drone:*`` prefixed STAC Item properties.

        Omits None / empty-string / empty-dict values so the STAC Item stays
        clean when most fields are unavailable.

        Follows the naming convention of the COP STAC Extension
        (stac-extensions.github.io/cop).
        """
        raw = asdict(self)
        out: Dict[str, Any] = {}
        # Fields that map directly to STAC as-is (no prefix)
        DIRECT = {"latitude", "longitude", "altitude_m", "time_utc"}
        for k, v in raw.items():
            if v is None or v == "" or v == {}:
                continue
            if k in DIRECT:
                out[k] = v
            else:
                out[f"drone:{k}"] = v
        return out

    def to_moving_feature_dict(self) -> Dict[str, Any]:
        """Return a dict formatted as a COP backend ``DroneTrackPoint`` POST body.

        Can be sent directly to ``POST /api/moving-features/drones``.
        """
        d = asdict(self)
        # Backend requires latitude/longitude at top level — already present.
        # Remove fields that are always None and not required by the backend.
        return {k: v for k, v in d.items() if v is not None and v != {}}


# ---------------------------------------------------------------------------
# Private helpers
# ---------------------------------------------------------------------------

def _sensor_dims_for_model(model: str) -> tuple:
    """Return (sensor_width_mm, sensor_height_mm) for the given model string.

    Falls back to DJI Mini 2 / entry-level 1/2.3" sensor if unknown.
    """
    low = model.lower()
    for fragment, dims in _SENSOR_DIMS.items():
        if fragment in low:
            return dims
    return (6.17, 4.63)   # 1/2.3" default


def _resolve_type_info(code: int) -> Dict[str, Any]:
    """Look up DRONE_TYPES entry from the backend moving_feature_types module.

    Gracefully degrades if the backend package is not importable (e.g. when
    running in a standalone QGIS environment without the Cesium dashboard).
    """
    try:
        # Prefer the sibling backend module when available
        import importlib
        mft = importlib.import_module(
            "backend.moving_feature_types",
            package=None,
        )
        return mft.DRONE_TYPES.get(code, mft.DRONE_TYPES[0])
    except (ImportError, KeyError):
        pass

    # Fallback: minimal inline table covering the most common codes
    _FALLBACK: Dict[int, Dict[str, Any]] = {
        0:  {"mav_type": 0,  "stanag_4586_class": "",    "faa_category": "",          "mgcp_fcode": "GB015"},
        1:  {"mav_type": 2,  "stanag_4586_class": "",    "faa_category": "Part 107",  "mgcp_fcode": "GB015"},
        2:  {"mav_type": 2,  "stanag_4586_class": "",    "faa_category": "Part 107",  "mgcp_fcode": "GB015"},
        3:  {"mav_type": 11, "stanag_4586_class": "",    "faa_category": "Part 107",  "mgcp_fcode": "GB015"},
        10: {"mav_type": 2,  "stanag_4586_class": "",    "faa_category": "Part 107",  "mgcp_fcode": "GB015"},
        11: {"mav_type": 2,  "stanag_4586_class": "",    "faa_category": "Part 107",  "mgcp_fcode": "GB015"},
        20: {"mav_type": 2,  "stanag_4586_class": "I",   "faa_category": "Public UA", "mgcp_fcode": "GB015"},
        21: {"mav_type": 2,  "stanag_4586_class": "II",  "faa_category": "Public UA", "mgcp_fcode": "GB015"},
        22: {"mav_type": 11, "stanag_4586_class": "III", "faa_category": "Public UA", "mgcp_fcode": "GB015"},
        40: {"mav_type": 20, "stanag_4586_class": "",    "faa_category": "Rec/Sport", "mgcp_fcode": "GB015"},
    }
    entry = _FALLBACK.get(code, _FALLBACK[0])
    return entry
